#!/bin/bash
# =============================================================================
# Script 5: Open Source Manifesto Generator
# Author: Ishan Baghel | Roll Number: 24BCE10485
# Course: Open Source Software | OSS Capstone Project
# Software Chosen: Git (GPL v2)
# Description: Interactively asks the user three questions and composes a
#              personalised open-source philosophy manifesto, saving it to a
#              .txt file named after the current user.
# =============================================================================

# --- Aliases concept demonstration ---
# Aliases are shortcuts for longer commands, commonly used in ~/.bashrc
# They cannot be defined and used within the same non-interactive script,
# but we demonstrate the concept here as comments and via shell functions.
# alias today='date +%d-%B-%Y'   # Example: 'today' would run the date command
# alias greet='echo Hello, $USER' # Example: personalised greeting alias

# --- Helper function (similar concept to an alias, but more powerful) ---
# Functions in bash are reusable blocks — like aliases but with logic
print_section() {
    echo ""
    echo "------------------------------------------------------------"
    echo "  $1"     # $1 is the first argument passed to the function
    echo "------------------------------------------------------------"
}

# --- Header ---
clear   # Clear the terminal for a clean interactive experience
echo "============================================================"
echo "       OPEN SOURCE MANIFESTO GENERATOR — OSS Audit         "
echo "============================================================"
echo ""
echo "  This script will ask you three questions and compose"
echo "  a personalised open-source philosophy statement."
echo "  Your manifesto will be saved to a .txt file."
echo ""
echo "============================================================"
echo ""

# --- Interactive input using 'read' with prompts ---
# read -p displays the prompt on the same line as the cursor
# The answer is stored in the variable named after -p's text

read -p "  1. Name one open-source tool you use every day: " TOOL
echo ""

read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""

read -p "  3. Name one thing you would build and share freely: " BUILD
echo ""

# --- Validate that the user actually entered something ---
# -z checks if a variable is empty (zero length)
if [ -z "$TOOL" ] || [ -z "$FREEDOM" ] || [ -z "$BUILD" ]; then
    echo "  ERROR: All three questions must be answered."
    echo "  Please run the script again and provide all answers."
    exit 1
fi

# --- Date and output filename ---
DATE=$(date '+%d %B %Y')                # Human-readable date: 31 March 2026
TIME=$(date '+%H:%M:%S')                # Time of generation
OUTPUT="manifesto_$(whoami).txt"        # Filename includes current username

print_section "GENERATING YOUR MANIFESTO..."
sleep 1     # Brief pause for dramatic effect

# --- Compose the manifesto using string concatenation and >> (append) ---
# We use > first to create/overwrite the file, then >> to append lines

# Write the header to the file (> creates or overwrites)
echo "============================================================" > "$OUTPUT"
echo "           MY OPEN SOURCE MANIFESTO                        " >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"
echo "  Generated by : $(whoami)"                                   >> "$OUTPUT"
echo "  Date         : $DATE at $TIME"                              >> "$OUTPUT"
echo "  Course       : Open Source Software — OSS Capstone"         >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"
echo ""                                                             >> "$OUTPUT"

# --- Compose the personalised paragraph using the three answers ---
# String variables are concatenated by placing them inline in echo statements

echo "  Every day, I rely on $TOOL — a piece of software that" >> "$OUTPUT"
echo "  someone chose to build in the open and share freely with" >> "$OUTPUT"
echo "  the world. That single act of generosity is what open" >> "$OUTPUT"
echo "  source means to me." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  To me, freedom means $FREEDOM. In the world of software," >> "$OUTPUT"
echo "  freedom is not just the ability to run a program — it is" >> "$OUTPUT"
echo "  the right to understand it, to change it, and to pass it" >> "$OUTPUT"
echo "  on. A tool that hides its source is a tool that cannot be" >> "$OUTPUT"
echo "  fully trusted, because trust requires transparency." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  If I could build anything and share it freely, I would" >> "$OUTPUT"
echo "  build $BUILD. I would release it under an open-source" >> "$OUTPUT"
echo "  license — not because I have to, but because I believe" >> "$OUTPUT"
echo "  that knowledge grows when it is shared and shrinks when" >> "$OUTPUT"
echo "  it is hoarded. Standing on the shoulders of giants is" >> "$OUTPUT"
echo "  only meaningful if you reach down and offer your hand" >> "$OUTPUT"
echo "  to those who come after you." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  This is my commitment to the open-source way." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Closing signature ---
echo "  Signed: $(whoami)"          >> "$OUTPUT"
echo "  Date  : $DATE"              >> "$OUTPUT"
echo ""                             >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"

# --- Confirm save and display the manifesto ---
print_section "MANIFESTO SAVED TO: $OUTPUT"
echo ""

# cat reads and prints the file contents to the terminal
cat "$OUTPUT"

echo ""
echo "============================================================"
echo "  Your manifesto has been saved to: $OUTPUT"
echo "  You can view it any time with:  cat $OUTPUT"
echo "  Or share it freely — that is the open-source way."
echo "============================================================"
